In [52]:
import pandas as pd
import numpy as np
#df_org=pd.read_csv(filepath+"application_train_merge_clear_nomissing .csv")
df_org=pd.read_csv("application_train_merge_clear_nomissing_with_ylabel.csv")

In [53]:
df=df_org

## 資料切分

In [54]:
y_=[]#找出 違約人的索引
for i in (df[df["TARGET"]!=0].index):
  y_.append(i)
y_1=[] #找出沒違約人的索引
for i in (df[df["TARGET"]==0].index):
  y_1.append(i)
df_split=df.loc[y_]
df_split0=df.loc[y_1]
df_tar1=df_split.reset_index()
df_tar0=df_split0.reset_index()
df_tar_e=df_tar0.iloc[:24825,:] #分成同等分
dfe=pd.concat([df_tar_e,df_tar1],ignore_index=True,axis=0)

In [55]:
df_X = dfe[['DAYS_BIRTH', 'DAYS_EMPLOYED', 'DAYS_REGISTRATION', 'DAYS_ID_PUBLISH',
       'DAYS_LAST_PHONE_CHANGE', 'AMT_ARREARS', 'YIELD_high',
       'bureau_DAYS_CREDIT', 'bureau_DAYS_ENDDATE_FACT',
       'bureau_DAYS_CREDIT_UPDATE']]
df_y = dfe['TARGET']

In [56]:
from sklearn.model_selection import train_test_split
#X , y = df_X.iloc[257511:,:] , df_y.iloc[257511:]
X , y = df_X  , df_y
X_train, X_test, y_train, y_test =\
    train_test_split(X, y, 
                     test_size=0.2,#超過10萬9,1分比較好 
                     random_state=0, 
                     stratify=y)

In [57]:
X_train.shape

(39720, 10)

In [58]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import RepeatedStratifiedKFold
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3)#, random_state=1)
# 建立Logistic模型
logisticModel = LogisticRegression()#random_state=1)
# 使用訓練資料訓練模型
logisticModel.fit(X_train, y_train)
# 使用訓練資料預測分類
predicted = logisticModel.predict(X_train)

/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [59]:
print('訓練集: ',logisticModel.score(X_train,y_train))
print('測試集: ',logisticModel.score(X_test,y_test))

訓練集:  0.576913393756294
測試集:  0.5695871097683787


In [60]:
print('分類的預測結果：')
pred = logisticModel.predict(X_test) 
print(pred) #觀察預測結果AA
print('真實數據：')
print(y_test.values)  #觀察真實數據(Test data)

分類的預測結果：
[1. 0. 1. ... 0. 0. 0.]
真實數據：
[0. 1. 1. ... 0. 0. 0.]


In [61]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, pred)

0.5695871097683787

In [51]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, pred)

array([[2758, 2207],
       [2091, 2874]])